# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class Vpc:
        type: str
    class WebApp:
        type: str
        url: str

